services:
  pocketbase:
    image: 'ghcr.io/coollabsio/pocketbase:latest'
    ports:
      - 8080:8080
    volumes:
      - 'pocketbase-data:/app/pb_data'
      - 'pocketbase-hooks:/app/pb_hooks'

volumes:
  pocketbase-data:
  pocketbase-hooks:
