# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: airsoft-market
    ports:
      - 5432:5432
    volumes:
      - /var/folders/postgres:/var/lib/postgresql/data/
