import "./globals.css";
import Link from "next/link";
import Providers from "./providers";
import UserPanel from "$/components/UserPanel";
import Navbar from "$/components/Navbar";

export const metadata = {
  title: {
    default: "Soft Occaz",
    template: "%s | Soft Occaz",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-zinc-900 text-zinc-300">
        <Providers>
          <header className="sticky top-0 z-20 p-4 bg-zinc-900 lg:px-20">
            <div className="flex items-end gap-5 text-zinc-50">
              <div className="flex-1">
                <ul className="flex gap-5">
                  <li>
                    <Link href="/">Home</Link>
                  </li>
                  <li>
                    <Link href="/ads">Annonces</Link>
                  </li>
                </ul>
              </div>
              <UserPanel />
            </div>
            <div>
              <Navbar />
            </div>
          </header>
          <main className="container mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
