import "tailwindcss/tailwind.css";
import Providers from "./providers";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-zinc-900 text-zinc-300">
        <Providers>
          <header className="flex items-end gap-5">
            <h1 className="text-4xl font-bold ">Pocketbase</h1>
            <div>
              <ul>
                <li>
                  <Link href="/">Home</Link>
                </li>
              </ul>
            </div>
          </header>
          <main className="container mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
