import './globals.css';

import Link from 'next/link';

import Navbar from '$/components/Navbar';
import UserPanel from '$/components/UserPanel';

import Providers from './providers';

export const metadata = {
  title: {
    default: 'Soft Occaz',
    template: '%s | Soft Occaz',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="bg-slate-900 text-slate-300">
        <Providers>
          <header className="sticky top-0 z-20 shadow bg-slate-900 shadow-slate-800">
            <div className="flex items-end gap-5 py-5 text-2xl lg:px-10 text-slate-50">
              <div className="flex-1">
                <ul className="flex gap-5">
                  <li>
                    <Link href="/">Home</Link>
                  </li>
                  <li>
                    <Link href="/ads">Annonces</Link>
                  </li>
                </ul>
              </div>
              <UserPanel />
            </div>
            <div className="lg:px-20">
              <Navbar />
            </div>
          </header>
          <main className="container mx-auto mt-10">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
